import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/features/auth/context/AuthProvider";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  weight: ["400", "500"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  weight: ["400", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <AuthProvider> {children} </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}